/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
 import { Match } from './match';

 export class SecondQuarter { 
     id?: number;
     type?: number;
     numberofplay?: number;
     codeteam?: string;
     playerId?: string;
     playtype?: string;
     player?: string;
     team?: string;
     dorsal?: string;
     minute?: number;
     markertime?: string;
     pointsA?: string;
     pointsB?: string;
     comment?: string;
     playinfo?: string;
     match?: Match;
     markAsFavourite?: boolean;
 }